/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());

        Vehicle vehicleA = new Vehicle("A", "Audi");
        vehicleA.speedUp(30);

        Vehicle vehicleB = new Vehicle("B", "BMW");
        vehicleB.speedUp(50);

        Car carA = new Car("C", "NewCar");
        carA.speedUp(200);
        carA.speedUp(201);
    }
}